### ISSUE TITLE
Réservations sur des créneaux en dehors de la plage définie

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/GRR-MuE#3]
Dans l'ancienne version l'affichage est moyen mais bien géré (pas en dehors du tableau).
cf : https://test-lycee.reciaent.fr/grr/grr2/public/week.php?year=2017&month=05&day=12&room=888

Par contre dans la nouvelle version les créneaux arrivant après sont affichés en dehors du tableau.
cf : https://test-lycee.reciaent.fr/grr/grr31/week.php?year=2017&month=05&day=12&room=888

**Comment by cdaviau** [comment]
Corrigé par Théo en contrôlant les saisies de réservations.
